-- Idempotent seed data. Safe to re-run.

-- FDI/ISO-3950 tooth numbering: permanent teeth + primary/deciduous teeth.
insert into teeth (fdi_number, name, dentition_type) values
  ('18', 'Upper right third molar', 'permanent'),
  ('17', 'Upper right second molar', 'permanent'),
  ('16', 'Upper right first molar', 'permanent'),
  ('15', 'Upper right second premolar', 'permanent'),
  ('14', 'Upper right first premolar', 'permanent'),
  ('13', 'Upper right canine', 'permanent'),
  ('12', 'Upper right lateral incisor', 'permanent'),
  ('11', 'Upper right central incisor', 'permanent'),
  ('21', 'Upper left central incisor', 'permanent'),
  ('22', 'Upper left lateral incisor', 'permanent'),
  ('23', 'Upper left canine', 'permanent'),
  ('24', 'Upper left first premolar', 'permanent'),
  ('25', 'Upper left second premolar', 'permanent'),
  ('26', 'Upper left first molar', 'permanent'),
  ('27', 'Upper left second molar', 'permanent'),
  ('28', 'Upper left third molar', 'permanent'),
  ('38', 'Lower left third molar', 'permanent'),
  ('37', 'Lower left second molar', 'permanent'),
  ('36', 'Lower left first molar', 'permanent'),
  ('35', 'Lower left second premolar', 'permanent'),
  ('34', 'Lower left first premolar', 'permanent'),
  ('33', 'Lower left canine', 'permanent'),
  ('32', 'Lower left lateral incisor', 'permanent'),
  ('31', 'Lower left central incisor', 'permanent'),
  ('41', 'Lower right central incisor', 'permanent'),
  ('42', 'Lower right lateral incisor', 'permanent'),
  ('43', 'Lower right canine', 'permanent'),
  ('44', 'Lower right first premolar', 'permanent'),
  ('45', 'Lower right second premolar', 'permanent'),
  ('46', 'Lower right first molar', 'permanent'),
  ('47', 'Lower right second molar', 'permanent'),
  ('48', 'Lower right third molar', 'permanent'),
  ('55', 'Upper right second primary molar', 'primary'),
  ('54', 'Upper right first primary molar', 'primary'),
  ('53', 'Upper right primary canine', 'primary'),
  ('52', 'Upper right primary lateral incisor', 'primary'),
  ('51', 'Upper right primary central incisor', 'primary'),
  ('61', 'Upper left primary central incisor', 'primary'),
  ('62', 'Upper left primary lateral incisor', 'primary'),
  ('63', 'Upper left primary canine', 'primary'),
  ('64', 'Upper left first primary molar', 'primary'),
  ('65', 'Upper left second primary molar', 'primary'),
  ('75', 'Lower left second primary molar', 'primary'),
  ('74', 'Lower left first primary molar', 'primary'),
  ('73', 'Lower left primary canine', 'primary'),
  ('72', 'Lower left primary lateral incisor', 'primary'),
  ('71', 'Lower left primary central incisor', 'primary'),
  ('81', 'Lower right primary central incisor', 'primary'),
  ('82', 'Lower right primary lateral incisor', 'primary'),
  ('83', 'Lower right primary canine', 'primary'),
  ('84', 'Lower right first primary molar', 'primary'),
  ('85', 'Lower right second primary molar', 'primary')
on conflict (fdi_number) do nothing;
